### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [JaerenTredway/prj-rev-bwfs-dasmoto#6]
https://github.com/JaerenTredway/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css#L6-L34

Nice job using more general selectors like so that you can consolidate shared styles in one location and keep your CSS tidy and maintainable. 👍 

If a style is going to be applied by default, considering using the universal selector `*` so that you don't have to write a selector listing every single tag on the page.

For example:

```css
* {
  font-weight: Helvetica;
}
```

**Comment by JaerenTredway** [comment]
I've heard that using the universal selector * can significantly slow down how fast the page loads if the page has a huge amount of code. In your experience do you think this is an issue? I would definitely like to use it if there's no issue.
